/**
 * SkillContext — per-job ICP and decision-maker targeting context.
 *
 * Auto-generated by generateExtractionPlan from the user's description.
 * Stored as skillContextJson (JSON text) in enrichmentJobs.
 * Injected into planNextAction and extractProfileFields for every scrape in the job.
 */
export interface SkillContext {
  /** One-sentence description of the ideal target company. */
  icpSummary: string;
  /** Observable signals on the company website that indicate a good fit. */
  fitSignals: string[];
  /** Observable signals that mean the company should be skipped. */
  exclusionSignals: string[];
  /** Job titles most likely to be the right decision maker for this use case, in priority order. */
  targetTitles: string[];
  /** One sentence explaining why these companies are being researched. */
  outreachGoal: string;
}
